---

- name: Check to see if k3s_state is a supported value
  assert:
    that:
      - k3s_state in k3s_valid_states
    fail_msg: "k3s_state not valid. Check README.md for details."
    success_msg: "k3s_state is valid."
  when: k3s_state is defined

- include_tasks: state-{{ (k3s_state | lower) | default('installed') }}.yml
