---

- name: Ensure Docker repository is uninstalled
  ansible.builtin.apt_repository:
    filename: docker-ce
    repo: "deb https://download.docker.com/linux/{{ k3s_os_distribution }} {{ ansible_distribution_release }} stable"
    update_cache: false
    state: absent
  become: "{{ k3s_become_for_uninstall | ternary(true, false, k3s_become_for_all) }}"

- name: Ensure Docker APT key is uninstalled
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ k3s_os_distribution }}/gpg
    state: absent
  become: "{{ k3s_become_for_uninstall | ternary(true, false, k3s_become_for_all) }}"
