---

- name: Check if any experimental variables are configure and if they are enabled with k3s_use_experimental
  assert:
    that:
      - k3s_use_experimental is defined and k3s_use_experimental
    success_msg: "Experimental variables are defined and enabled."
    fail_msg: "Experimental variables have been configured. If you want to use them ensure you set k3s_use_experimental"
  when: (k3s_server.rootless is defined and k3s_server.rootless)
        or (k3s_agent.rootless is defined and k3s_agent.rootless)
        or (k3s_server.etcd-datastore is defined and k3s_server.etcd-datastore)
        or (k3s_server.secrets-encryption is defined and k3s_server.secrets-encryption)
        or (k3s_agent.secrets-encryption is defined and k3s_agent.secrets-encryption)
        or (k3s_server.selinux is defined and k3s_server.selinux)
