---

- name: Check that the control plane to is available to accept connections
  wait_for:
    port: "{{ k3s_https_port }}"
    host: "{{ k3s_bind_address | default('127.0.0.1') }}"
    delay: 5
    sleep: 5
    timeout: 300
  when: k3s_control_node
