---

- name: Check that k3s_release_version >= 1.19.0
  assert:
    that:
      - (k3s_release_version | replace('v', '')) is version_compare('1.19.0', '>=')
    success_msg: "{{ k3s_release_version }} is supported by this role."
    fail_msg: "{{ k3s_release_version }} is not supported by this role, please use xanmanning.k3s v1.x."

# Due to the v2 role now only supporting k3s v1.19+ - this file is intentionlly
# blank until new configuration options are added.
