---

- name: Check that k3s_release_version >= 1.19.0
  assert:
    that:
      - (k3s_release_version | replace('v', '')) is version_compare('1.19.0', '>=')
    success_msg: "{{ k3s_release_version }} is supported by this role."
    fail_msg: "{{ k3s_release_version }} is not supported by this role, please use xanmanning.k3s v1.x."

- name: Check configuration in k3s_server and k3s_agent
  assert:
    that:
      - (item.setting not in k3s_runtime_config)
    success_msg: "{{ item.setting }} not found in server/agent config"
    fail_msg: "{{ item.setting }} found in server/agent config. Please set {{ item.correction }} to use this option."
  loop: "{{ k3s_config_exclude }}"

# Due to the v2 role now only supporting k3s v1.19+ - this file is intentionlly
# blank until new configuration options are added.
