---

- import_tasks: check-variables.yml

- import_tasks: check-experimental-variables.yml

- import_tasks: check-unsupported-rootless.yml
  when: ("rootless" in k3s_runtime_config)
        and k3s_runtime_config.rootless

- import_tasks: check-control-count.yml
  when: k3s_build_cluster is defined and k3s_build_cluster
