---

- include_tasks: environment/remote/packages.yml
  loop: "{{ k3s_check_packages[k3s_os_distribution_version] }}"
  loop_control:
    loop_var: package
  when:
    - not k3s_skip_validation
    - not k3s_skip_env_checks
    - k3s_check_packages[k3s_os_distribution_version] is defined

- import_tasks: configuration/variables.yml

- import_tasks: configuration/experimental-variables.yml

- import_tasks: configuration/unsupported-rootless.yml
  when:
    - k3s_runtime_config.rootless is defined
    - k3s_runtime_config.rootless

- import_tasks: configuration/control-node-count.yml
  when:
    - k3s_build_cluster is defined
    - k3s_build_cluster
