---

- name: Ensure Docker repository is removed
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/{{ k3s_os_distribution }}/{{ ansible_distribution_major_version }}/$basearch/stable
    gpgkey: https://download.docker.com/linux/{{ k3s_os_distribution }}/gpg
    enabled: false
    gpgcheck: true
    state: absent
  when: k3s_os_distribution not in ['amazon']
  become: "{{ k3s_become_for_uninstall | ternary(true, false, k3s_become_for_all) }}"
